#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RECORD_PATH="$REPO_ROOT/docs/release/evidence/issue-16-manual-accessibility.md"
EVIDENCE_PATH="$REPO_ROOT/docs/release/manual-evidence.json"
SUPPORTED_CODEX_VERSION="26.901.41600 (build 7982)"

require_confirm() {
  if ! confirm "$1"; then
    warn "This release check cannot pass until the answer is yes. No evidence was changed."
    exit 1
  fi
}

banner "Codex Git VoiceOver release check"

stage "Record the macOS assistive-technology environment"
say "This stage records public version information; no secrets are collected."
MACOS_VERSION=$(sw_vers -productVersion)
note "Detected macOS $MACOS_VERSION"
open_url "x-apple.systempreferences:com.apple.Accessibility-Settings.extension"
step "Open VoiceOver settings, then VoiceOver Utility → About, and note its displayed version."
ask VOICEOVER_VERSION "VoiceOver / VoiceOver Utility version:"
step "In Codex, open About Codex and copy the version including its build number."
ask CODEX_VERSION "Codex Desktop version (for example 26.901.41600 (build 7982)):"
step "Record the Chromium/WebView version from the tested Codex compatibility profile."
ask WEBVIEW_VERSION "Chromium/WebView version:"
if [[ "$CODEX_VERSION" != "$SUPPORTED_CODEX_VERSION" ]]; then
  warn "Issue #16 currently supports only Codex Desktop $SUPPORTED_CODEX_VERSION."
  warn "Add and verify a new compatibility profile before running this release check."
  exit 1
fi
require_confirm "Are these versions taken from the machine and Codex build you will test now?"

stage "Complete Git workflows without a pointer"
say "The wizard will create a disposable Repository and local bare Remote. It never touches your real branches or remotes."
FIXTURE_ROOT=$(mktemp -d /private/tmp/codex-git-voiceover.XXXXXX)
REMOTE_PATH="$FIXTURE_ROOT/remote.git"
SEED_PATH="$FIXTURE_ROOT/seed"
WORK_PATH="$FIXTURE_ROOT/work"
LINKED_PATH="$FIXTURE_ROOT/linked"
UNAVAILABLE_PATH="$FIXTURE_ROOT/unavailable"
UNAVAILABLE_HIDDEN_PATH="$FIXTURE_ROOT/unavailable-hidden"
CONFLICT_PATH="$FIXTURE_ROOT/conflict"
git init --quiet --bare "$REMOTE_PATH"
git init --quiet --initial-branch=main "$SEED_PATH"
git -C "$SEED_PATH" config user.name "Codex Git VoiceOver"
git -C "$SEED_PATH" config user.email "voiceover@example.test"
printf 'initial\n' > "$SEED_PATH/README.md"
printf 'base\n' > "$SEED_PATH/conflict.txt"
git -C "$SEED_PATH" add -- README.md conflict.txt
git -C "$SEED_PATH" commit --quiet -m "Create VoiceOver fixture"
git -C "$SEED_PATH" branch review-branch
git -C "$SEED_PATH" branch linked-smoke
git -C "$SEED_PATH" branch unavailable-smoke
git -C "$SEED_PATH" branch conflict-smoke
printf 'main change\n' > "$SEED_PATH/conflict.txt"
git -C "$SEED_PATH" commit --quiet -am "Create main conflict side"
git -C "$SEED_PATH" switch --quiet conflict-smoke
printf 'branch change\n' > "$SEED_PATH/conflict.txt"
git -C "$SEED_PATH" commit --quiet -am "Create branch conflict side"
git -C "$SEED_PATH" switch --quiet main
git -C "$SEED_PATH" remote add origin "$REMOTE_PATH"
git -C "$SEED_PATH" push --quiet --all origin
git clone --quiet --branch main "$REMOTE_PATH" "$WORK_PATH"
git -C "$WORK_PATH" config user.name "Codex Git VoiceOver"
git -C "$WORK_PATH" config user.email "voiceover@example.test"
git -C "$WORK_PATH" branch linked-smoke origin/linked-smoke
git -C "$WORK_PATH" worktree add --quiet "$LINKED_PATH" linked-smoke
git -C "$WORK_PATH" branch unavailable-smoke origin/unavailable-smoke
git -C "$WORK_PATH" worktree add --quiet "$UNAVAILABLE_PATH" unavailable-smoke
git -C "$WORK_PATH" branch conflict-smoke origin/conflict-smoke
git -C "$WORK_PATH" worktree add --quiet "$CONFLICT_PATH" conflict-smoke
if git -C "$CONFLICT_PATH" merge --quiet origin/main; then
  warn "The conflict fixture merged unexpectedly."
  exit 1
fi
printf 'changed for keyboard review\n' > "$WORK_PATH/README.md"
printf 'untracked keyboard target\n' > "$WORK_PATH/keyboard-target.txt"
say "Fixture ready at: $WORK_PATH"
step "In a second Terminal window, run this command and keep it running:"
say "cd '$REPO_ROOT' && CODEX_GIT_PROJECT_PATH='$WORK_PATH' CODEX_GIT_SURFACE_PORT=0 npm run dev"
pause "Press Enter only after the Git Surface is visible in the dedicated Codex window."
step "Confirm there is exactly one Git entry and one full-page Git Surface, then select a native Codex destination and reopen Git."
require_confirm "Did native navigation restore the Codex content with no hidden overlay, and did reopening Git create only one surface?"
step "With Git open, reload the dedicated Codex renderer (Command-R), wait for the Git entry to return, and open it again."
require_confirm "After renderer reload, did exactly one Git entry and one fresh surface return without leaving a hidden overlay?"
step "Use only the keyboard to Refresh, review both Changed Files, Stage and Unstage one exact file, then Stage and Commit the intended files."
require_confirm "Did review, Stage, Unstage, and Commit work with visible focus and exact target names?"
step "Use only the keyboard to Push the new main Commit to its exact origin/main Upstream."
require_confirm "Did Push succeed without including any uncommitted content?"
git -C "$SEED_PATH" pull --quiet --ff-only origin main
printf 'remote update\n' > "$SEED_PATH/remote-update.txt"
git -C "$SEED_PATH" add -- remote-update.txt
git -C "$SEED_PATH" commit --quiet -m "Create remote update"
git -C "$SEED_PATH" push --quiet origin main
step "A remote-only Commit now exists. Use only the keyboard to Fetch and then Pull it by fast-forward."
require_confirm "Did Fetch and Pull expose and apply the exact origin/main update?"
step "Open the Branch picker and switch to the cached Remote-tracking review-branch target."
require_confirm "Did Branch switch create/select only the same-name Local tracking Branch?"
git -C "$WORK_PATH" switch --quiet -c publish-smoke
printf 'publish fixture\n' > "$WORK_PATH/publish-smoke.txt"
git -C "$WORK_PATH" add -- publish-smoke.txt
git -C "$WORK_PATH" commit --quiet -m "Create unpublished fixture"
step "The watcher has moved to an unpublished Local Branch. Use only the keyboard to Publish it to origin/publish-smoke."
require_confirm "Did Publish show and use the exact Remote and same-name target?"
if ! git -C "$WORK_PATH" ls-remote --exit-code --heads origin refs/heads/publish-smoke >/dev/null; then
  warn "origin/publish-smoke was not created; the Publish check did not reconcile."
  exit 1
fi
step "Navigate to an exact Worktree, Branch, and Changed File target and verify the announced target matches the visible target."
require_confirm "Did exact-target navigation remain keyboard reachable and unambiguous?"

stage "Verify VoiceOver announcements and focus recovery"
step "Turn VoiceOver on (Command-F5 on supported keyboards) and return to the Git Surface without using a pointer."
require_confirm "Is keyboard focus always visibly indicated and announced?"
step "Repeat controls that appear for multiple Worktrees/files and listen for the exact Worktree, file, Branch, or Remote name."
require_confirm "Do repeated controls announce their exact targets?"
step "Trigger Refresh and an operation result; verify the live status is announced without moving focus away from the current control."
require_confirm "Are status and operation changes announced without stealing focus?"
step "Focus the linked-smoke Worktree in the navigator, then return here. The wizard will remove it externally."
pause "Press Enter when focus is on linked-smoke and you are ready for removal."
git -C "$WORK_PATH" worktree remove --force "$LINKED_PATH"
pause "Wait for the Git Surface to observe the removal, then press Enter."
require_confirm "Did focus recover to the nearest safe context with an understandable announcement?"
mv "$UNAVAILABLE_PATH" "$UNAVAILABLE_HIDDEN_PATH"
step "The unavailable-smoke Worktree path is now absent while its registration remains. Refresh, then inspect Clean, changed, Conflict, unavailable, stale/transitioning status, and operation outcomes."
require_confirm "Is every state understandable through text and VoiceOver without relying on color?"

stage "Write evidence and run the release gate"
SOURCE_REVISION=$(cd "$REPO_ROOT" && npx tsx -e "import('./tests/release/manual-evidence.ts').then(async ({collectProductSourceRevision}) => console.log(await collectProductSourceRevision(process.cwd())))")
PERFORMED_AT=$(date -u +'%Y-%m-%dT%H:%M:%S.000Z')
VALID_UNTIL=$(date -u -v+28d +'%Y-%m-%dT%H:%M:%S.000Z')
ENVIRONMENT="macOS $MACOS_VERSION; VoiceOver $VOICEOVER_VERSION; Codex Desktop $CODEX_VERSION; Chromium/WebView $WEBVIEW_VERSION"
mkdir -p "$(dirname "$RECORD_PATH")"
cat > "$RECORD_PATH" <<EOF
# Codex host, VoiceOver, and keyboard release check

- Status: passed
- Performed at: $PERFORMED_AT
- Valid until: $VALID_UNTIL
- Product source revision: $SOURCE_REVISION
- Environment: $ENVIRONMENT

## Passing observations

- The exact Codex compatibility profile attached one Git entry and one surface, restored native navigation, and remounted once after renderer reload without duplication.
- Refresh, review, Stage, Unstage, Commit, Branch switch, Fetch, Pull, Push, and Publish were completed without a pointer.
- Visible focus and VoiceOver target names identified the exact Worktree, file, Branch, and Remote.
- Live status and operation results were announced without stealing focus.
- Focus recovered to a safe context after the focused linked Worktree disappeared.
- Clean, changed, unavailable, stale, transitioning, and operation states remained understandable without color.
EOF
MANUAL_EVIDENCE_PATH="$EVIDENCE_PATH" \
MANUAL_CODEX_VERSION="$CODEX_VERSION" \
MANUAL_ENVIRONMENT="$ENVIRONMENT" \
MANUAL_PERFORMED_AT="$PERFORMED_AT" \
MANUAL_SOURCE_REVISION="$SOURCE_REVISION" \
MANUAL_VALID_UNTIL="$VALID_UNTIL" \
node --input-type=module - <<'NODE'
import { readFile, writeFile } from 'node:fs/promises';

const path = process.env.MANUAL_EVIDENCE_PATH;
const evidence = JSON.parse(await readFile(path, 'utf8'));
for (const id of ['codex-host-smoke', 'voiceover-keyboard-smoke']) {
  const check = evidence.checks.find((candidate) => candidate.id === id);
  if (check === undefined) throw new Error(`Manual check ${id} is absent.`);
  Object.assign(check, {
    codexVersion: process.env.MANUAL_CODEX_VERSION,
    environment: process.env.MANUAL_ENVIRONMENT,
    performedAt: process.env.MANUAL_PERFORMED_AT,
    record: 'docs/release/evidence/issue-16-manual-accessibility.md',
    sourceRevision: process.env.MANUAL_SOURCE_REVISION,
    status: 'passed',
    validUntil: process.env.MANUAL_VALID_UNTIL,
  });
}
await writeFile(path, `${JSON.stringify(evidence, null, 2)}\n`, 'utf8');
NODE
say "Evidence written to $RECORD_PATH and $EVIDENCE_PATH."
step "The full gate will now run on the approved local macOS profile. It takes about one minute."
(cd "$REPO_ROOT" && \
  CODEX_DESKTOP_VERSION="$CODEX_VERSION" \
  CODEX_GIT_REFERENCE_PROFILE=local-macos-release \
  npm run release:gate)
require_confirm "Did the release gate finish with 'Release gate: passed'?"
note "Stop the second Terminal process with Ctrl-C when finished."
note "Disposable fixture (safe to delete after stopping Codex Git): $FIXTURE_ROOT"

finish
